---

name: build

on:
  workflow_call:
    inputs:
      build_arch:
        required: true
        type: string
        default: 'all'
  workflow_dispatch: ~

permissions:
  contents: read

## Concurrency only allowed in the main branch.
## So old builds running for old commits within the same Pull Request are cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build-native:
    uses: ./.github/workflows/build-native.yml
    with:
      build_arch: all

  build-php-deps:
    uses: ./.github/workflows/build-php-deps.yml

  build-packages:
    needs:
      - build-native
      - build-php-deps
    uses: ./.github/workflows/build-packages.yml
    with:
      build_arch: all
