---

# Generates matrix for component tests
name: generate-component-tests-matrix

on:
  workflow_call:
    outputs:
      matrix:
        description: "Matrix for component tests"
        value: ${{ jobs.generate-component-tests-matrix.outputs.matrix }}

permissions:
  contents: read

jobs:
  generate-component-tests-matrix:
    name: generate-component-tests-matrix
    timeout-minutes: 5
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: generate
        run: |
          MATRIX=$(./tools/test/generate_component_tests_matrix.sh | jq --raw-input --slurp -c 'split("\n") | map(select(length > 0)) | map(split(",")) | map({ "row": . } )')
          echo "matrix=${MATRIX}"
          echo "matrix=${MATRIX}" >> $GITHUB_OUTPUT
