---

name: test-php-static-check

on:
  workflow_call: ~
  workflow_dispatch: ~

permissions:
  contents: read

jobs:
  generate-php-versions:
    uses: ./.github/workflows/generate-php-versions.yml

  static-check:
    runs-on: ubuntu-latest
    needs: generate-php-versions
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-php-versions.outputs.php-versions) }}
    env:
      PHP_VERSION: ${{ matrix.php-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Invoke test_php_static_check.sh
        run: ./tools/build/test_php_static_check.sh --php_versions "${PHP_VERSION}"
